baseURL = "https://juan.codes/"
languageCode = "en-us"
disableKinds = ["taxonomy"]

[build]
    writeStats = true

[params]
    title = "Sada Theme"
    author = "Juan Rodriguez"
    description = "About Me"
    copyright = "Â© Juan Rodriguez 2025"
    theme = "dark" # `dark` or `light`

    # Profile section
    [params.profile]
        name = "Juan Rodriguez"
        title = "Software Developer"
        photo = "images/profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "bi bi-linkedin"
        url = "https://linkedin.com/in/juanabr/"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "bi bi-github"
        url = "https://github.com/juan-abr/"
        title = "GitHub"
		
        # [[params.social.list]]
        # icon = "bi bi-mortarboard-fill"
        # url = "#"
        # title = "Google Scholar"

        # [[params.social.list]]
        # icon = "bi bi-envelope-at-fill"		
        # url = "#"
        # title = "Email"

        # [[params.social.list]]
        # icon = "bi bi-bluesky"
        # url = "#"
        # title = "Bluesky"

        [[params.social.list]]
        icon = "bi bi-instagram"
        url = "https://instagram.com/juanabrod/"
        title = "Instagram"

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "B.S. Information Systems Management"
        college = "University of Maryland Global Campus"
        dates = "Dec. 2019"
        # thesis_title = "Title of the dissertation"
        # thesis_link = "#"

        [[params.education.list]]
        degree = "A.S. Information Systems Management"
        college = "Frederick Community College"
        dates = "May 2017"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        # [[params.language.list]]
        # language = "Bird"
        # level = "Basic"

    # Interests section
    [params.hobbies]
        title = "Hobbies"

        [[params.hobbies.list]]
        interest = "Travelling"
		
		[[params.hobbies.list]]
        interest = "Music"

        [[params.hobbies.list]]
        interest = "Flying"

        [[params.hobbies.list]]
        interest = "Baking"

    [params.aboutme]
        description = "Individually driven to leverage experience in agile development and scrum, and to utilize my major as it pertains to Information Systems Management. Eager to fill an software development or IT support role with a local company promoting personal growth and development."

    # Experiences section
    [params.experiences]
        title = "Experiences"

        [[params.jobs.list]]
        position = "Web Developer"
        dates = "Sept. 2023 - *Present*"
		link = "https://cmmartialarts.com/"
        company = "Central Maryland Martial Arts"
        details = "Spearheaded development of several web applications for local martial arts studio using Django web framework and SQL relational database with Amazon Web Services."

        [[params.jobs.list]]
        position = "Software Development Intern"
        dates = "Jan. 2022 - June 2022"
		link = "https://ihire.com/"
        company = "iHire, LLC"
        details = "Directed unit, feature, and system-level testing to fulfill bug fix requests for job board and talent acquisition platform. Participated in collaborative sprints, scrums, and multi-departmental meetings to identify challenges and follow ticket/story progression. Utilized software development tools including MiniProfiler, Visual Studio, and Postman. Added new JavaScript libraries, terms and conditions, and beta features to production website."

    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "TechFrederick 2020 Hackathon"
        url = "https://techfrederick.com/"
        description = "Earned one of 3 overall first place spots during a 2-week online programming competition hosted in 2020 with TechFrederick, by successfully developing a records management system for Frederick, MD Fire and Rescue utilizing the Django web framework."
		
        # [[params.projects.list]]
        # title = "Awesome Project 2"
        # url = "#"
        # description = "Description of the **awesome** project 2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

        # [[params.projects.list]]
        # title = "Awesome Project 3"
        # url = "#"
        # description = "Description of the **awesome** project 2. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "Skill 1, Skill 2"
        skillrating = 95 # out of 100
                
        [[params.skills.list]]
        skill = "Skill 3"
        skillrating = 90
		
        [[params.skills.list]]
        skill = "Skill 4"
        skillrating = 80
